#python Postprocess_SAM.py '/lustre/ytzheng/' 'ASTEX_cold2.6'
#python Postprocess_SAM.py '/lustre/ytzheng/' 'ASTEX_cold2.6_fxdlhf'
#python Postprocess_SAM.py '/lustre/ytzheng/' 'ASTEX_warm2.6'
#python Postprocess_SAM.py '/lustre/ytzheng/' 'ASTEX_warm5.2'
#python Postprocess_SAM.py '/lustre/ytzheng/' 'ASTEX_warm2.6_Div3'
#python Postprocess_SAM.py '/lustre/ytzheng/' 'ASTEX_cold2.6_240x240'
#python Postprocess_SAM.py '/lustre/ytzheng/' 'ASTEX_cold2.6_fxdlhf_240x240'
python Postprocess_SAM.py '/lustre/ytzheng/' 'ASTEX_warm2.6_240x240'